### ISSUE TITLE
Invalid odoc resolution

### ISSUE THREAD

**Issue by boyswan** [ostera/reactor#7]
Package.json resolutions are trying to reference a relative link and erroring.

```
info esy 0.5.6 (using package.json)
error: ../odoc doesn't exist
  reading package metadata from link:../odoc/odoc.opam
```

**Comment by leostera** [comment]
Oops! Thanks for this. I’ll get to fix it in the next hour or so 🙏🏼

**Comment by boyswan** [comment]
No worries! Also when building `/examples` the relative resolution to reactor.opam causes a weird recursive pathname error. Removing that and running `esy` again returns

```
info installing: done
Error: I don't know about package reactor-examples (passed through --only-packages/--release)
error: command failed: 'refmterr' 'dune' 'build' '-p' 'reactor-examples' (exited with 1)
esy-build-package: exiting with errors above...
error: build failed with exit code: 1

esy: exiting due to errors above
```

Sorry for jumping in with issues already - just excited to try it out!

**Comment by leostera** [comment]
A-ha, interesting! I've locked it to the latest master but I need to find a better way of keeping the examples pointing to it.
